name: ci

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  test-js:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['11', '17']
    env:
      JAVA_OPTS: "-Xss10M"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Run JS tests
        run: |
          ./mill -i -j 0 -k __.js.__.compile + __.js.__.publishArtifacts + __.js.__.test

  test-native:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['11', '17']
    env:
      JAVA_OPTS: "-Xss10M"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Run Native tests
        run: |
          ./mill -i -j 0 -k __.native.__.compile + __.native.__.publishArtifacts + __.native.__.test

  test-jvm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['11', '17']
    env:
      JAVA_OPTS: "-Xss10M"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Run JVM tests
        run: |
          ./mill -i -j 0 -k __.jvm.__.compile + __.jvm.__.publishArtifacts + __.jvm.__.test

  check-binary-compatibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Check Binary Compatibility
        run: ./mill -i -k __.mimaReportBinaryIssues

  publish-sonatype:
    if: github.repository == 'com-lihaoyi/upickle' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    env:
      MILL_SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      MILL_SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      MILL_PGP_SECRET_BASE64: ${{ secrets.SONATYPE_PGP_PRIVATE_KEY }}
      MILL_PGP_PASSPHRASE: ${{ secrets.SONATYPE_PGP_PRIVATE_KEY_PASSWORD }}
      LANG: "en_US.UTF-8"
      LC_MESSAGES: "en_US.UTF-8"
      LC_ALL: "en_US.UTF-8"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Publish to Maven Central
        run: ./mill -i mill.scalalib.SonatypeCentralPublishModule/
        
      - name: Create GitHub Release
        id: create_gh_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
